# Generated by Django 3.2.14 on 2022-07-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('base', models.CharField(max_length=50)),
                ('chief', models.CharField(max_length=50)),
                ('chassis', models.CharField(max_length=50)),
                ('powerunit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pilotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('podiums', models.IntegerField()),
                ('points', models.FloatField()),
                ('Date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pistas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('length', models.FloatField(max_length=50)),
                ('record', models.FloatField(max_length=50)),
            ],
        ),
    ]
