# Generated by Django 3.2.14 on 2022-07-23 23:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CODER_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilotos',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pilotos',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pilotos',
            name='points',
            field=models.IntegerField(),
        ),
    ]
