# Generated by Django 3.2.14 on 2022-08-11 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CODER_APP', '0002_blog_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='date',
            new_name='fecha_post',
        ),
    ]
