# Generated by Django 3.2.14 on 2022-08-11 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CODER_APP', '0003_rename_date_blog_fecha_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentarios',
        ),
    ]
