# Generated by Django 3.2.14 on 2022-08-11 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CODER_APP', '0005_blog_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='imagen',
            new_name='imagenBlog',
        ),
    ]
