# Generated by Django 3.2.14 on 2022-08-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CODER_APP', '0009_alter_message_reciever'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='Foto/equipos'),
        ),
        migrations.AddField(
            model_name='pilotos',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='Foto/pilotos'),
        ),
        migrations.AddField(
            model_name='pistas',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='Foto/pistas'),
        ),
    ]
